title: OnlyWorlds
description: Documentation for the OnlyWorlds world building framework
theme: just-the-docs

url: https://onlyworlds.github.io

logo: "/assets/images/OWLogo.png"
favicon_ico: "/assets/images/favicon.ico"
color_scheme: dark

# Custom CSS
aux_links_new_tab: false
custom_css: "/assets/css/custom.css"

exclude:
  - archive/
